version: '27.0'
services:
  postgres:  # database-name
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: den
      POSTGRES_PASSWORD: 456
      POSTGRES_DB: blog_app
    networks:
      - den
  redis:
    image: redis:latest
    ports: 
      - 6379:6379
networks:
  den: 